version: '3'

services:
  apache:
    build: .docker/apache
    container_name: symfony_apache
    ports:
      - "8000:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ./app:/home/wwwroot/app
    depends_on:
      - php

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  php:
    build: .docker/php
    container_name: symfony_php
    volumes:
      - ./app:/home/wwwroot/app
    environment:
      - maildev_host=symfony_maildev
    depends_on:
      - maildev
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: symfony_maildev
    ports:
      - "8001:80"


#version: '3'
#
#services:
####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-13}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jaslo}
#      POSTGRES_USER: ${POSTGRES_USER:-symfony}
#    volumes:
#      - db-data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  db-data:
####< doctrine/doctrine-bundle ###
